/**
 * Error Highlighting User Study — Main Application (v2: Flag Mode)
 *
 * Changes from v1:
 *   - Plan review uses Flag mode: click each step as ✅ "Correct" or ⚠️ "Has Problem"
 *   - No more edit/add/delete — lower cognitive load, cleaner data
 *   - Pre-study simplified to 2 questions: LLM usage frequency + AI trust baseline
 */

/* ============================================================
   State
   ============================================================ */
const state = {
  participantId: null,
  counterbalanceGroup: null,
  currentPage: "welcome",
  consent: {},
  demographics: {},
  conditionOrder: [],
  conditionA_tasks: [],
  conditionB_tasks: [],
  taskResults: {},
  nasaTlx: { conditionA: {}, conditionB: {} },
  postTask: {},
  interview: {},
  studyStartTime: null,
  pageStartTime: null,
  timestamps: {},
};

/* ============================================================
   Page Flow
   ============================================================ */
const PAGE_FLOW = [
  "welcome",
  "info-sheet",
  "consent-form",
  "pre-study",
  "tutorial",
  "condA-task1",
  "condA-task2",
  "nasa-tlx-A",
  "break",
  "condB-task1",
  "condB-task2",
  "nasa-tlx-B",
  "post-task",
  "interview",
  "thank-you",
];
const TOTAL_PAGES = PAGE_FLOW.length;

/* ============================================================
   Init
   ============================================================ */
document.addEventListener("DOMContentLoaded", () => {
  initFirebase();
  assignParticipant();
  renderPage("welcome");
  updateProgress();
});

function assignParticipant() {
  state.participantId = "P" + Date.now().toString(36).toUpperCase();
  let counter = parseInt(localStorage.getItem("cb_counter") || "0");
  const group = COUNTERBALANCE_GROUPS[counter % COUNTERBALANCE_GROUPS.length];
  state.counterbalanceGroup = group.groupId;
  state.conditionOrder = group.conditionOrder;
  state.conditionA_tasks = group.conditionA_tasks;
  state.conditionB_tasks = group.conditionB_tasks;
  localStorage.setItem("cb_counter", String(counter + 1));
  state.studyStartTime = Date.now();
}

/* ============================================================
   Navigation & Progress
   ============================================================ */
function navigateTo(pageId) {
  if (state.pageStartTime) {
    state.timestamps[state.currentPage] = (state.timestamps[state.currentPage] || 0) + (Date.now() - state.pageStartTime);
  }
  state.currentPage = pageId;
  state.pageStartTime = Date.now();
  renderPage(pageId);
  updateProgress();
  window.scrollTo({ top: 0, behavior: "smooth" });
}

function updateProgress() {
  const idx = PAGE_FLOW.indexOf(state.currentPage);
  const pct = Math.round(((idx + 1) / TOTAL_PAGES) * 100);
  const fill = document.getElementById("progress-fill");
  const label = document.getElementById("progress-label");
  if (fill) fill.style.width = pct + "%";
  if (label) label.textContent = `Step ${idx + 1} of ${TOTAL_PAGES}`;
}

/* ============================================================
   Page Router
   ============================================================ */
function renderPage(pageId) {
  const c = document.getElementById("page-content");
  switch (pageId) {
    case "welcome":      renderWelcome(c); break;
    case "info-sheet":   renderInfoSheet(c); break;
    case "consent-form": renderConsentForm(c); break;
    case "pre-study":    renderPreStudy(c); break;
    case "tutorial":     renderTutorial(c); break;
    case "condA-task1":  renderTask(c, 0, 0); break;
    case "condA-task2":  renderTask(c, 0, 1); break;
    case "nasa-tlx-A":  renderNasaTlx(c, "conditionA"); break;
    case "break":        renderBreak(c); break;
    case "condB-task1":  renderTask(c, 1, 0); break;
    case "condB-task2":  renderTask(c, 1, 1); break;
    case "nasa-tlx-B":  renderNasaTlx(c, "conditionB"); break;
    case "post-task":    renderPostTask(c); break;
    case "interview":    renderInterview(c); break;
    case "thank-you":    renderThankYou(c); break;
  }
}

/* ============================================================
   Welcome
   ============================================================ */
function renderWelcome(c) {
  c.innerHTML = `
    <div class="study-page active">
      <div class="card" style="text-align:center; padding:3rem 2rem;">
        <h2 style="font-size:1.6rem; margin-bottom:0.5rem;">Welcome to the User Study</h2>
        <p style="color:var(--text-secondary); margin-bottom:0.5rem;">
          Investigating the Effect of Error Highlighting on User Trust<br>
          in LLM-Generated Plans
        </p>
        <div class="cambridge-badge" style="margin:0.75rem auto;">
          🎓 Department of Engineering, University of Cambridge
        </div>
        <p class="info-text" style="max-width:520px; margin:1.5rem auto 0;">
          Thank you for your interest. The session takes approximately
          <strong>10–12 minutes</strong>. You will review plans generated by an AI assistant
          and flag any steps you think contain errors.
        </p>
        <div class="btn-group center" style="margin-top:2rem;">
          <button class="btn btn-primary" onclick="navigateTo('info-sheet')">Begin →</button>
        </div>
        <p class="info-text" style="margin-top:1rem; font-size:0.78rem;">
          Participant ID: <code style="font-family:var(--font-mono);">${state.participantId}</code>
        </p>
      </div>
    </div>`;
}

/* ============================================================
   Information Sheet
   ============================================================ */
function renderInfoSheet(c) {
  c.innerHTML = `
    <div class="study-page active">
      <div class="card">
        <h2>Participant Information Sheet</h2>
        <p class="info-text" style="margin-bottom:1rem;">Please read the following information carefully before deciding whether to take part.</p>
        <div class="scrollable-content">
          <h4>Purpose of the Study</h4>
          <p>This study evaluates whether error highlighting in AI-generated plans helps users identify mistakes and calibrate their trust. The findings will contribute to understanding of human-AI collaboration with Large Language Model (LLM) agents.</p>
          <h4>1. Why have I been chosen?</h4>
          <p>You have been invited because you have prior experience using LLM-based tools (e.g., ChatGPT). This ensures you can meaningfully engage with the task of reviewing LLM-generated plans.</p>
          <h4>2. Do I have to take part?</h4>
          <p>No, participation is entirely voluntary. You can withdraw at any time without giving any reasons.</p>
          <h4>3. Who is organising the study?</h4>
          <p>This study is conducted as part of the MLMI16 module at the Department of Engineering, University of Cambridge. The principal investigator is Dr John Dudley.</p>
          <h4>4. What will happen during the study?</h4>
          <p>You will review four AI-generated plans for everyday tasks. For each step in the plan, you will indicate whether you think it is correct or contains an error. In some cases, potential errors will be visually highlighted. After reviewing plans, you will answer short questionnaires about your experience.</p>
          <h4>5. What are the possible risks?</h4>
          <p>This study poses minimal risk. All tasks are simulated with no real consequences. The session lasts approximately 10–12 minutes.</p>
          <h4>6. What happens at the end?</h4>
          <p>You will have a chance to ask any questions. Your anonymised results may be included in a coursework report.</p>
          <h4>7. Will I be identified?</h4>
          <p>No. All data is anonymised using unique identifiers.</p>
          <h4>8. What if there is a problem?</h4>
          <p>Please contact the researcher(s) who will do their best to answer your questions.</p>
          <h4>9. Who has reviewed the study?</h4>
          <p>The Department of Engineering Ethics Committee has reviewed this study through the light-touch review process.</p>
        </div>
        <div class="btn-group center">
          <button class="btn btn-secondary" onclick="navigateTo('welcome')">← Back</button>
          <button class="btn btn-primary" onclick="navigateTo('consent-form')">Continue →</button>
        </div>
      </div>
    </div>`;
}

/* ============================================================
   Consent Form
   ============================================================ */
function renderConsentForm(c) {
  const items = [
    "I confirm that I have read and understand the Participant Information Sheet.",
    "I have had the opportunity to ask questions and have had these answered satisfactorily.",
    "I understand that my participation is voluntary and that I am free to withdraw at any time without giving a reason.",
    "I agree that data gathered in this study may be stored anonymously and securely, and may be used for future research.",
    "I agree that my anonymised responses may be included in a coursework report and potentially presented at research meetings.",
    "I agree to take part in this study.",
  ];
  c.innerHTML = `
    <div class="study-page active">
      <div class="card">
        <h2>Participant Consent Form</h2>
        <p class="info-text" style="margin-bottom:1.25rem;">Please tick <strong>all</strong> boxes to confirm your consent.</p>
        <div style="margin-bottom:0.75rem;">
          <button class="btn btn-small btn-secondary" onclick="selectAllConsent()">Select All</button>
        </div>
        <div id="consent-items">
          ${items.map((t, i) => `
            <div class="consent-item">
              <input type="checkbox" id="consent-${i}" onchange="checkConsent()">
              <span>${i + 1}. ${t}</span>
            </div>`).join("")}
        </div>
        <p class="validation-error" id="consent-error">Please confirm all items to proceed.</p>
        <div class="btn-group center">
          <button class="btn btn-secondary" onclick="navigateTo('info-sheet')">← Back</button>
          <button class="btn btn-primary" id="consent-btn" disabled onclick="submitConsent()">I Consent — Continue →</button>
        </div>
      </div>
    </div>`;
}

function checkConsent() {
  const all = Array.from(document.querySelectorAll('#consent-items input')).every(b => b.checked);
  document.getElementById("consent-btn").disabled = !all;
}

function selectAllConsent() {
  document.querySelectorAll('#consent-items input').forEach(b => b.checked = true);
  checkConsent();
}

function submitConsent() {
  state.consent = { consented: true, timestamp: new Date().toISOString() };
  saveToFirebase(state.participantId, { consent: state.consent, counterbalanceGroup: state.counterbalanceGroup });
  navigateTo("pre-study");
}

/* ============================================================
   Pre-Study (Simplified: 2 questions only)
   ============================================================ */
function renderPreStudy(c) {
  c.innerHTML = `
    <div class="study-page active">
      <div class="card">
        <h2>Quick Background Questions</h2>
        <p class="info-text" style="margin-bottom:1.5rem;">Just two quick questions before we begin.</p>

        <div class="form-group">
          <label>How often do you use LLM-based tools (e.g., ChatGPT, Claude)? <span class="required-star">*</span></label>
          <div class="radio-group">
            ${["Daily", "Several times a week", "Once a week", "A few times a month", "Rarely"].map(v => `
              <label class="radio-option"><input type="radio" name="llm_freq" value="${v}"> ${v}</label>`).join("")}
          </div>
        </div>

        <div class="form-group">
          <label>In general, how much do you trust AI systems to provide accurate information? <span class="required-star">*</span></label>
          <div class="likert-container" style="background:transparent; padding:0;">
            <div class="likert-scale">
              ${[1,2,3,4,5,6,7].map(v => `<label><input type="radio" name="ai_trust" value="${v}"> ${v}</label>`).join("")}
            </div>
            <div class="likert-endpoints"><span>1 — Not at all</span><span>7 — Completely</span></div>
          </div>
        </div>

        <p class="validation-error" id="prestudy-error">Please answer both questions.</p>
        <div class="btn-group center">
          <button class="btn btn-secondary" onclick="navigateTo('consent-form')">← Back</button>
          <button class="btn btn-primary" onclick="submitPreStudy()">Continue →</button>
        </div>
      </div>
    </div>`;
}

function submitPreStudy() {
  const freq = document.querySelector('input[name="llm_freq"]:checked');
  const trust = document.querySelector('input[name="ai_trust"]:checked');
  if (!freq || !trust) {
    document.getElementById("prestudy-error").classList.add("visible");
    return;
  }
  state.demographics = { llm_freq: freq.value, ai_trust: trust.value };
  saveToFirebase(state.participantId, { demographics: state.demographics });
  navigateTo("tutorial");
}

/* ============================================================
   Tutorial
   ============================================================ */
function renderTutorial(c) {
  c.innerHTML = `
    <div class="study-page active">
      <div class="card">
        <h2>Tutorial: How the Study Works</h2>
        <div class="tutorial-highlight">
          <span class="icon">💡</span>
          <strong>Please read this carefully before starting.</strong>
        </div>

        <h3>Your Task</h3>
        <p>An AI assistant has generated step-by-step plans for everyday tasks. Your job is to <strong>review each step</strong> and decide whether it looks correct or might contain an error.</p>

        <hr class="divider">

        <h3>How to Review</h3>
        <p>For each step in the plan, click one of two buttons:</p>
        <div style="display:flex; gap:1rem; margin:1rem 0; flex-wrap:wrap;">
          <div style="flex:1; min-width:200px; padding:1rem; background:var(--success-bg); border:1px solid #a3d9a8; border-radius:var(--radius-sm); text-align:center;">
            <span style="font-size:1.3rem;">✅</span><br>
            <strong>Looks Correct</strong><br>
            <span class="info-text">This step appears accurate</span>
          </div>
          <div style="flex:1; min-width:200px; padding:1rem; background:var(--error-highlight-bg); border:1px solid var(--error-highlight-border); border-radius:var(--radius-sm); text-align:center;">
            <span style="font-size:1.3rem;">⚠️</span><br>
            <strong>Has a Problem</strong><br>
            <span class="info-text">This step may contain an error</span>
          </div>
        </div>
        <p>After reviewing all steps, you'll indicate whether you <strong>trust the overall plan</strong> to produce a correct result.</p>

        <hr class="divider">

        <h3>About Error Highlighting</h3>
        <p>In some tasks, certain steps will be marked with a <span class="error-icon" style="display:inline-flex; vertical-align:middle;">⚠</span> warning icon and a <span style="border-left:4px solid var(--error-highlight); padding-left:6px; background:var(--error-highlight-bg); display:inline; padding:2px 6px; border-radius:3px;">red border</span>. These suggest the step <em>may</em> contain an error. However:</p>
        <div class="tutorial-highlight">
          <strong>Important:</strong> The highlighting is not perfect — it may miss some errors, and highlighted steps may not always be wrong. Always review <em>all</em> steps carefully.
        </div>

        <div class="btn-group center" style="margin-top:2rem;">
          <button class="btn btn-primary" onclick="navigateTo('condA-task1')">I understand — Start the study →</button>
        </div>
      </div>
    </div>`;
}

/* ============================================================
   Task Rendering (Flag Mode)
   ============================================================ */
function getTaskInfo(condIdx, taskIdx) {
  const ids = condIdx === 0 ? state.conditionA_tasks : state.conditionB_tasks;
  return {
    task: TASKS.find(t => t.id === ids[taskIdx]),
    condition: state.conditionOrder[condIdx],
    taskId: ids[taskIdx],
  };
}

function renderTask(c, condIdx, taskIdx) {
  const { task, condition, taskId } = getTaskInfo(condIdx, taskIdx);
  const pageKey = condIdx === 0
    ? (taskIdx === 0 ? "condA-task1" : "condA-task2")
    : (taskIdx === 0 ? "condB-task1" : "condB-task2");

  // Init task result
  if (!state.taskResults[taskId]) {
    state.taskResults[taskId] = {
      condition, taskId, risk: task.risk,
      stepFlags: {},    // stepId -> "correct" | "problem"
      trustJudgment: null,
      startTime: Date.now(),
      endTime: null,
    };
  }

  const condLabel = condition === "treatment" ? "With Error Highlighting" : "Without Error Highlighting";
  const taskNum = condIdx * 2 + taskIdx + 1;

  c.innerHTML = `
    <div class="study-page active">
      <div class="card">
        <div style="display:flex; justify-content:space-between; align-items:center; margin-bottom:1rem;">
          <h2 style="margin-bottom:0;">Task ${taskNum} of 4</h2>
          <span class="condition-badge">${condLabel}</span>
        </div>

        <div class="task-briefing">
          <div class="task-label">
            ${task.domain} Task
            <span class="risk-badge ${task.risk}">${task.risk} risk</span>
          </div>
          <p style="margin-top:0.5rem; font-size:0.95rem;">"${task.description}"</p>
        </div>

        <div class="plan-container">
          <div class="plan-header">
            <h3>AI-Generated Plan — Review each step</h3>
          </div>
          <div class="plan-steps" id="plan-steps-${taskId}">
            ${renderFlagSteps(task.plan, condition, taskId)}
          </div>
        </div>

        <p class="validation-error" id="flag-error-${taskId}">Please review all steps before continuing.</p>

        <div class="trust-judgment" id="trust-${taskId}" style="display:none;">
          <p>Do you trust this plan to produce the correct execution result?</p>
          <div class="trust-buttons">
            <button class="trust-btn yes" onclick="submitTrust('${taskId}', true, ${condIdx}, ${taskIdx})">👍 Yes, I trust it</button>
            <button class="trust-btn no" onclick="submitTrust('${taskId}', false, ${condIdx}, ${taskIdx})">👎 No, I don't trust it</button>
          </div>
        </div>

        <div id="execution-${taskId}" class="hidden">
          <div class="execution-result success">
            <h4>✅ Execution Result</h4>
            <p>${task.executionResult.summary}</p>
          </div>
          <div class="btn-group center">
            <button class="btn btn-primary" id="next-btn-${taskId}">Continue →</button>
          </div>
        </div>
      </div>
    </div>`;
}

/**
 * Render plan steps with flag buttons (no edit/add/delete)
 */
function renderFlagSteps(steps, condition, taskId, depth = 0) {
  let html = "";
  for (const step of steps) {
    const cls = depth === 0 ? "primary" : depth === 1 ? "sub" : "sub-sub";
    const isHL = condition === "treatment" && step.hasHighlightedError;
    const hlCls = isHL ? "error-highlighted" : "";

    // Steps with children are grouping headers — no flag buttons needed
    const hasChildren = step.children && step.children.length > 0;

    html += `<div class="plan-step ${cls} ${hlCls}" data-step-id="${step.id}" data-task-id="${taskId}">
      <div class="plan-step-content">
        ${isHL ? '<span class="error-icon">⚠</span>' : ""}
        <span class="plan-step-text">${step.text}</span>
        ${!hasChildren ? `
          <div class="flag-buttons" id="flags-${taskId}-${step.id}">
            <button class="flag-btn correct" onclick="flagStep('${taskId}','${step.id}','correct')" title="Looks correct">✅</button>
            <button class="flag-btn problem" onclick="flagStep('${taskId}','${step.id}','problem')" title="Has a problem">⚠️</button>
          </div>` : ""}
      </div>
    </div>`;

    if (step.children) {
      html += renderFlagSteps(step.children, condition, taskId, depth + 1);
    }
  }
  return html;
}

/**
 * Handle step flagging
 */
function flagStep(taskId, stepId, value) {
  state.taskResults[taskId].stepFlags[stepId] = value;

  // Update button styles
  const container = document.getElementById(`flags-${taskId}-${stepId}`);
  if (container) {
    container.querySelectorAll(".flag-btn").forEach(b => b.classList.remove("selected"));
    const sel = value === "correct" ? container.querySelector(".correct") : container.querySelector(".problem");
    if (sel) sel.classList.add("selected");
  }

  // Update the step's visual style
  const stepEl = document.querySelector(`[data-step-id="${stepId}"][data-task-id="${taskId}"]`);
  if (stepEl) {
    stepEl.classList.remove("flagged-correct", "flagged-problem");
    stepEl.classList.add(value === "correct" ? "flagged-correct" : "flagged-problem");
  }

  // Check if all flaggable steps have been reviewed
  checkAllFlagged(taskId);
}

function checkAllFlagged(taskId) {
  const flagBtnContainers = document.querySelectorAll(`[id^="flags-${taskId}-"]`);
  const totalSteps = flagBtnContainers.length;
  const flaggedCount = Object.keys(state.taskResults[taskId].stepFlags).length;

  if (flaggedCount >= totalSteps) {
    // Show trust judgment
    document.getElementById(`trust-${taskId}`).style.display = "";
    document.getElementById(`flag-error-${taskId}`).classList.remove("visible");
  }
}

/**
 * Submit trust judgment & advance
 */
function submitTrust(taskId, trusted, condIdx, taskIdx) {
  // Highlight selected
  const btns = document.querySelectorAll(`#trust-${taskId} .trust-btn`);
  btns.forEach(b => b.classList.remove("selected"));
  btns[trusted ? 0 : 1].classList.add("selected");

  state.taskResults[taskId].trustJudgment = trusted;
  state.taskResults[taskId].endTime = Date.now();
  state.taskResults[taskId].duration = state.taskResults[taskId].endTime - state.taskResults[taskId].startTime;

  // Show execution result
  document.getElementById(`execution-${taskId}`).classList.remove("hidden");

  // Determine next page
  let nextPage;
  if (condIdx === 0 && taskIdx === 0) nextPage = "condA-task2";
  else if (condIdx === 0 && taskIdx === 1) nextPage = "nasa-tlx-A";
  else if (condIdx === 1 && taskIdx === 0) nextPage = "condB-task2";
  else nextPage = "nasa-tlx-B";

  document.getElementById(`next-btn-${taskId}`).onclick = () => {
    saveToFirebase(state.participantId, { taskResults: state.taskResults });
    navigateTo(nextPage);
  };

  document.getElementById(`execution-${taskId}`).scrollIntoView({ behavior: "smooth" });
}

/* ============================================================
   NASA-TLX
   ============================================================ */
function renderNasaTlx(c, condKey) {
  const condLabel = condKey === "conditionA" ? state.conditionOrder[0] : state.conditionOrder[1];
  const condDisplay = condLabel === "treatment" ? "With Error Highlighting" : "Without Error Highlighting";

  c.innerHTML = `
    <div class="study-page active">
      <div class="card">
        <h2>Workload Assessment (NASA-TLX)</h2>
        <p class="info-text" style="margin-bottom:0.5rem;">Rate the workload for the <strong>previous two tasks</strong>.</p>
        <p style="margin-bottom:1.5rem;"><span class="condition-badge">${condDisplay}</span></p>

        ${NASA_TLX_SCALES.map(s => `
          <div class="slider-container">
            <div class="slider-label">${s.label}</div>
            <div class="slider-description">${s.description}</div>
            <input type="range" min="0" max="100" value="50" step="5"
                   id="tlx-${condKey}-${s.id}"
                   oninput="document.getElementById('val-${condKey}-${s.id}').textContent=this.value">
            <div class="slider-endpoints"><span>${s.lowEnd}</span><span>${s.highEnd}</span></div>
            <div class="slider-value" id="val-${condKey}-${s.id}">50</div>
          </div>`).join("")}

        <div class="btn-group center">
          <button class="btn btn-primary" onclick="submitNasaTlx('${condKey}')">Continue →</button>
        </div>
      </div>
    </div>`;
}

function submitNasaTlx(condKey) {
  const data = {};
  NASA_TLX_SCALES.forEach(s => { data[s.id] = parseInt(document.getElementById(`tlx-${condKey}-${s.id}`).value); });
  state.nasaTlx[condKey] = data;
  saveToFirebase(state.participantId, { nasaTlx: state.nasaTlx });
  navigateTo(condKey === "conditionA" ? "break" : "post-task");
}

/* ============================================================
   Break
   ============================================================ */
function renderBreak(c) {
  c.innerHTML = `
    <div class="study-page active">
      <div class="card break-screen">
        <h2>Short Break</h2>
        <p style="color:var(--text-secondary);">You've completed the first half. Take a moment to rest.</p>
        <div class="timer" id="break-timer">1:00</div>
        <p class="info-text">Continue whenever you're ready.</p>
        <div class="btn-group center" style="margin-top:1.5rem;">
          <button class="btn btn-primary" onclick="navigateTo('condB-task1')">Continue to Next Section →</button>
        </div>
      </div>
    </div>`;
  let sec = 60;
  const el = document.getElementById("break-timer");
  const iv = setInterval(() => { sec--; if (sec <= 0) { clearInterval(iv); el.textContent = "0:00"; return; } el.textContent = `0:${sec.toString().padStart(2,"0")}`; }, 1000);
}

/* ============================================================
   Post-Task Questionnaire
   ============================================================ */
function renderPostTask(c) {
  c.innerHTML = `
    <div class="study-page active">
      <div class="card">
        <h2>Post-Task Questionnaire</h2>
        <p class="info-text" style="margin-bottom:1.5rem;">
          Rate the following based on your experience. <em>(1 = Strongly Disagree, 7 = Strongly Agree)</em>
        </p>

        ${POST_TASK_QUESTIONS.map(q => `
          <div class="likert-container">
            <div class="likert-question">${q.text}</div>
            <div class="likert-scale">
              ${[1,2,3,4,5,6,7].map(v => `<label><input type="radio" name="post-${q.id}" value="${v}"> ${v}</label>`).join("")}
            </div>
            <div class="likert-endpoints"><span>Strongly Disagree</span><span>Strongly Agree</span></div>
          </div>`).join("")}

        <p class="validation-error" id="posttask-error">Please answer all questions.</p>
        <div class="btn-group center">
          <button class="btn btn-primary" onclick="submitPostTask()">Continue →</button>
        </div>
      </div>
    </div>`;
}

function submitPostTask() {
  const data = {};
  let valid = true;
  POST_TASK_QUESTIONS.forEach(q => {
    const el = document.querySelector(`input[name="post-${q.id}"]:checked`);
    if (!el) { valid = false; return; }
    data[q.id] = parseInt(el.value);
  });
  if (!valid) { document.getElementById("posttask-error").classList.add("visible"); return; }
  state.postTask = data;
  saveToFirebase(state.participantId, { postTask: data });
  navigateTo("interview");
}

/* ============================================================
   Interview (Open-Ended)
   ============================================================ */
function renderInterview(c) {
  c.innerHTML = `
    <div class="study-page active">
      <div class="card">
        <h2>Feedback Questions</h2>
        <p class="info-text" style="margin-bottom:1.5rem;">Please share your thoughts. There are no right or wrong answers.</p>

        ${INTERVIEW_QUESTIONS.map(q => `
          <div class="form-group">
            <label>${q.text}</label>
            <textarea id="interview-${q.id}" rows="3" placeholder="Type your response here..."></textarea>
          </div>`).join("")}

        <div class="btn-group center">
          <button class="btn btn-primary" onclick="submitInterview()">Submit & Finish →</button>
        </div>
      </div>
    </div>`;
}

function submitInterview() {
  const data = {};
  INTERVIEW_QUESTIONS.forEach(q => {
    const el = document.getElementById(`interview-${q.id}`);
    data[q.id] = el ? el.value.trim() : "";
  });
  state.interview = data;

  const finalData = {
    participantId: state.participantId,
    counterbalanceGroup: state.counterbalanceGroup,
    conditionOrder: state.conditionOrder,
    consent: state.consent,
    demographics: state.demographics,
    taskResults: state.taskResults,
    nasaTlx: state.nasaTlx,
    postTask: state.postTask,
    interview: state.interview,
    timestamps: state.timestamps,
    totalDuration: Date.now() - state.studyStartTime,
    completedAt: new Date().toISOString(),
  };
  saveToFirebase(state.participantId, finalData);
  navigateTo("thank-you");
}

/* ============================================================
   Thank You
   ============================================================ */
function renderThankYou(c) {
  c.innerHTML = `
    <div class="study-page active">
      <div class="card thank-you">
        <div class="checkmark">✅</div>
        <h2>Thank You!</h2>
        <p style="color:var(--text-secondary); max-width:480px; margin:0.75rem auto 1.5rem;">
          Your responses have been recorded. Thank you for participating!
        </p>
        <p class="info-text" style="margin-bottom:1.5rem;">
          Participant ID: <code style="font-family:var(--font-mono);">${state.participantId}</code>
          <br>Duration: <code>${Math.round((Date.now() - state.studyStartTime) / 60000)} minutes</code>
        </p>
        <div class="card" style="text-align:left; background:var(--info-bg); border-color:#bdd4f0; max-width:500px; margin:0 auto;">
          <h3 style="font-size:1rem;">Debrief</h3>
          <p style="font-size:0.88rem; color:var(--text-secondary);">
            This study examined whether highlighting potential errors in AI-generated plans helps users
            identify mistakes and calibrate their trust. In the treatment condition, some (but not all)
            errors were highlighted — we also investigated whether highlighting might cause participants
            to overlook non-highlighted errors (a complacency effect).
          </p>
          <p style="font-size:0.88rem; color:var(--text-secondary); margin-top:0.5rem;">
            If you have questions, please contact the research team at the Department of Engineering, University of Cambridge.
          </p>
        </div>
        <div class="btn-group center" style="margin-top:1.5rem;">
          <button class="btn btn-secondary" onclick="downloadLocalData()">📥 Download My Data (Backup)</button>
        </div>
      </div>
    </div>`;
}
